world_size: 1 
experiment_name: "fullmodel"
datasets:
    synthetic_fg: "/home/jovyan/datasets/synthetic_psi/"
    bg: "/home/jovyan/datasets/matting/am-2k/background/train"
    ppm100: "/home/jovyan/kvanchiani/stylegan3/PPM-100/image"
    aim500: "/home/jovyan/datasets/AIM-500"
    am2k: 
        train_original: "/home/jovyan/datasets/matting/am-2k/train/original"
        train_mask: "/home/jovyan/datasets/matting/am-2k/train/mask"
        background: "/home/jovyan/datasets/matting/am-2k/background/train"
        validation_original: "/home/jovyan/datasets/matting/am-2k/validation/original/"
        validation_mask: "/home/jovyan/datasets/matting/am-2k/validation/mask/"
        validation_trimap: "/home/jovyan/datasets/matting/am-2k/validation/trimap/"
    tiktok: "/home/jovyan/datasets/tiktokdataset/dataset"
    p3m10k: "/home/jovyan/datasets/matting/P3M-10k"
    p3m10k_test:
        VAL500P:
            ROOT_PATH: "P3M-500-P/"
            ORIGINAL_PATH: "P3M-500-P/blurred_image/"
            MASK_PATH: "P3M-500-P/mask/"
            TRIMAP_PATH: "P3M-500-P/trimap/"
            SAMPLE_NUMBER: 500
        VAL500NP:
            ROOT_PATH: "P3M-500-NP/"
            ORIGINAL_PATH: "P3M-500-NP/original_image/"
            MASK_PATH: "P3M-500-NP/mask/"
            TRIMAP_PATH: "P3M-500-NP/trimap/"
            SAMPLE_NUMBER: 500
    MAX_SIZE_H: 1600
    MAX_SIZE_W: 1600
    image_crop: 800
    use_file_cache: False 
dataset_to_use: "P3M10KBlurred"
pretrained_model: "microsoft/swinv2-tiny-patch4-window8-256"  #"nielsr/mask2former-swin-base-youtubevis-2021" #"nvidia/mit-b2"
batch_size: 4
num_workers: 4
log_dir: "log"
checkpoint_dir: "checkpoints"
checkpoint: "stylematte_pure.pth"
distributed_addr: "localhost"
distributed_port: "12357"
image_size: 800
lr: 1e-5
epochs: 200
single_conv: True
disable_validation: False
warmup_steps: 2
validate_each_epoch: 2 
max_images_for_validation: 50
disable_mixed_precision: True
log_image_interval: 2000
log_image_number: 8
save_model_interval: 10000
lambda_losses: 
    default: 1.
    Laplassian: 0.5
    composition: 2.
